//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public string IdenficationNumber { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string College { get; set; }
        public string Department { get; set; }
        public string Telephone { get; set; }
        public string MatialStatus { get; set; }
        public string Address { get; set; }
        public string PreferenceAbouttheApartmentID { get; set; }
    }
}
