//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finances2
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal Billing { get; set; }
        public decimal Rent { get; set; }
        public decimal Total { get; set; }
    }
}
