//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public string ApartmentId { get; set; }
        public string Address { get; set; }
        public string Billing { get; set; }
        public string Rent { get; set; }
        public string Total { get; set; }
    }
}
