//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenceRequest
    {
        public string ID { get; set; }
        public System.DateTime SummisionDate { get; set; }
        public string NameOfResident { get; set; }
        public string Address { get; set; }
        public System.DateTime DatePromblemWasFixed { get; set; }
        public string NameOfEmployeethatFixedit { get; set; }
        public string PrombolemDescription { get; set; }
    }
}
