//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseingSystemEntities2 : DbContext
    {
        public HouseingSystemEntities2()
            : base("name=HouseingSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Finance> Finances { get; set; }
        public DbSet<Finances2> Finances2 { get; set; }
        public DbSet<MaintenceRequest> MaintenceRequests { get; set; }
        public DbSet<PreferenceAboutApartment> PreferenceAboutApartments { get; set; }
        public DbSet<Resident> Residents { get; set; }
        public DbSet<Table_1> Table_1 { get; set; }
    }
}
