//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public string IdenficatioNumber { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string College { get; set; }
        public string DepartmentOftheFamily { get; set; }
        public string TelephoneNumber { get; set; }
        public string MartialStatus { get; set; }
        public string Address { get; set; }
        public string PaymentthatisOutStanding { get; set; }
        public string PaymentResievedtoDate { get; set; }
        public string WeeklyPaymentExpected { get; set; }
    }
}
